// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

public class CoralClawPivotSubsystem extends SubsystemBase {
  // we dont know if this will be used
  /** Creates a new ExampleSubsystem. */
  public CoralClawPivotSubsystem(int motorID) {
    //crating the motors and such
  }
}
